# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install any needed packages specified in requirements.txt
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Define environment variable
ENV MOCK_BIGQUERY=1

# Run export_bigquery_to_gcs.py when the container launches
CMD ["python", "./export_bigquery_to_gcs.py"]

